# Generated by Django 5.0.7 on 2024-11-21 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('idChofer', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id Chofer')),
                ('nombreChofer', models.CharField(max_length=30, verbose_name='Nombre Chofer')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('horario1', models.TimeField(verbose_name='Horario 1')),
                ('horario2', models.TimeField(verbose_name='Horario 2')),
                ('horario3', models.TimeField(verbose_name='Horario 3')),
                ('FotoPerfil', models.ImageField(null=True, upload_to='imagenes', verbose_name='Foto Perfil')),
                ('destino', models.CharField(max_length=20, verbose_name='Destino')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('idPago', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id Pago')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Método de Pago')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número de Cuenta o Tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('idVehiculo', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id Vehiculo')),
                ('marcaVehiculo', models.CharField(max_length=20, verbose_name='Marca Vehiculo')),
                ('modeloVehiculo', models.CharField(max_length=20, verbose_name='Modelo Vehiculo')),
                ('patenteVehiculo', models.CharField(max_length=20, verbose_name='Patente Vehiculo')),
                ('FotoVehiculo', models.ImageField(null=True, upload_to='imagenes', verbose_name='Foto Vehiculo')),
                ('cupos', models.PositiveIntegerField(verbose_name='Cupos')),
            ],
        ),
        migrations.CreateModel(
            name='ZonaViaje',
            fields=[
                ('idZona', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Zona')),
                ('nombreZona', models.CharField(max_length=20, verbose_name='Nombre Zona')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('idPasajero', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id Pasajero')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Pasajero')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('FotoPerfil', models.ImageField(null=True, upload_to='imagenes', verbose_name='Foto Perfil')),
                ('metodos_pago', models.ManyToManyField(related_name='metodos_pago_pasajero', to='Reserva.metodopago')),
            ],
        ),
        migrations.AddField(
            model_name='metodopago',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago_pasajero', to='Reserva.pasajero'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id Reserva')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('estadoTexto', models.CharField(max_length=5, verbose_name='Estado Texto')),
                ('calificacion', models.PositiveIntegerField(default=0, verbose_name='Calificacion')),
                ('resena', models.CharField(max_length=255, verbose_name='Reseña')),
                ('respuesta', models.CharField(max_length=255, verbose_name='Respuesta')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chofer', to='Reserva.chofer')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pasajero', to='Reserva.pasajero')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_reservado', to='Reserva.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='chofer',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehiculo', to='Reserva.vehiculo'),
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id Comuna')),
                ('nombreComuna', models.CharField(max_length=20, verbose_name='Nombre Comuna')),
                ('ZonaViaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserva.zonaviaje', verbose_name='Zona Viaje')),
            ],
        ),
    ]
