# Generated by Django 5.0.7 on 2024-11-21 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comuna', to='Reserva.comuna'),
        ),
    ]
