# Generated by Django 5.0.7 on 2024-11-21 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0002_alter_chofer_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idTipo', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id Tipo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Tipo')),
            ],
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tipo', to='Reserva.tipo'),
        ),
    ]
