# Generated by Django 5.0.7 on 2024-11-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0004_metodopago_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(default='10:00', verbose_name='Horario'),
            preserve_default=False,
        ),
    ]
