# Generated by Django 5.0.7 on 2024-11-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0005_reserva_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='cupos',
        ),
        migrations.AddField(
            model_name='chofer',
            name='cupos',
            field=models.PositiveIntegerField(default=10, verbose_name='Cupos'),
            preserve_default=False,
        ),
    ]
