# Generated by Django 5.0.7 on 2024-11-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0006_remove_vehiculo_cupos_chofer_cupos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='FotoPerfil',
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='metodos_pago',
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='password',
        ),
        migrations.AddField(
            model_name='pasajero',
            name='rut',
            field=models.CharField(default='21682301k', max_length=10, verbose_name='Rut del Pasajero'),
            preserve_default=False,
        ),
    ]
