# Generated by Django 5.0.7 on 2024-11-25 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0008_admin_tipoadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Tipo_Admin', to='Reserva.tipoadmin'),
            preserve_default=False,
        ),
    ]
