# Generated by Django 5.0.7 on 2024-12-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0012_admin_rut_chofer_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('idTotem', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id Totem')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
                ('serie', models.CharField(max_length=50, verbose_name='Serie')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha')),
            ],
        ),
    ]
