# Generated by Django 5.0.7 on 2024-12-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0013_totem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('idSector', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id Sector')),
                ('nombreSector', models.CharField(max_length=20, verbose_name='Nombre Sector')),
            ],
        ),
    ]
