# Generated by Django 5.0.7 on 2024-12-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0017_reserva_emailacompanante1_reserva_emailacompanante2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='emailAcompanante1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico del Acompañante 1'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='emailAcompanante2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico del Acompañante 2'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='emailAcompanante3',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico del Acompañante 3'),
        ),
    ]
