# Generated by Django 5.0.7 on 2024-11-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0010_admin_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='fechaRegistro',
            field=models.DateField(null=True, verbose_name='Fecha Registro'),
        ),
        migrations.AddField(
            model_name='chofer',
            name='fechaRegistro',
            field=models.DateField(null=True, verbose_name='Fecha Registro'),
        ),
    ]
