# Generated by Django 5.0.7 on 2024-12-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0014_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='nombreSector',
            field=models.CharField(max_length=255, verbose_name='Nombre Sector'),
        ),
    ]
